"""
Django settings for StockPass project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

"""

from datetime import datetime, timedelta
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@dkeh$5uyw+yg1dax)wcnga)&s!e50dur1scf=8*^3gz5naohy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "StockPassCore",
    "SalesAndTransport",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://scorpion-abiding-structure.ngrok-free.dev",
]

# CORS_ALLOW_ALL_ORIGINS = True


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "sharply-wriggly-curvy.ngrok-free.dev",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ["*"]

ROOT_URLCONF = 'StockPass.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'StockPass.wsgi.application'
ASGI_APPLICATION = 'StockPass.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "StockPassBR"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=31),

    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,

    "AUTH_HEADER_TYPES": ("Bearer",),
}

AUTH_USER_MODEL = "StockPassCore.User"
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# APPEND_SLASH = True

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# === LOG DIRECTORY SETUP ===
BASE_LOG_DIR = BASE_DIR / "logs"
TODAY = datetime.today().strftime("%Y-%m-%d")
LOG_DIR = BASE_LOG_DIR / TODAY
LOG_DIR.mkdir(parents=True, exist_ok=True)

# === FORMATTERS ===
LOGGING_FORMATTERS = {
    "standard": {
        "format": "[{asctime}] {levelname} {name} — {message}",
        "style": "{",
    },
    "verbose": {
        "format": "[{asctime}] [{levelname}] {name} {module}:{lineno} — {message}",
        "style": "{",
    },
}


# === HANDLERS ===
def get_file_handler(filename, level="INFO"):
    return {
        "class": "logging.FileHandler",
        "filename": os.path.join(LOG_DIR, filename),
        "formatter": "verbose",
        "level": level,
    }


LOGGING_HANDLERS = {
    "console": {
        "class": "logging.StreamHandler",
        "formatter": "standard",
    },
    "file": get_file_handler("django.log", "INFO"),
    "errors_file": get_file_handler("errors.log", "ERROR"),
    # "users_file": get_file_handler("users.log", "DEBUG"),
    # "companies_file": get_file_handler("companies.log", "DEBUG"),
    # "inventory_file": get_file_handler("inventory.log", "DEBUG"),
    # "employees_file": get_file_handler("employees.log", "DEBUG"),
    # Add more as needed
}

# === LOGGERS ===
LOGGING_LOGGERS = {
    "django": {
        "handlers": ["console", "file", "errors_file"],
        "level": "INFO",
        "propagate": True,
    },
    "ninja": {
        "handlers": ["console", "file", "errors_file"],
        "level": "INFO",
        "propagate": False,
    },
    # "apps.users": {
    #     "handlers": ["console", "users_file"],
    #     "level": "DEBUG",
    #     "propagate": False,
    # },
    # "apps.companies": {
    #     "handlers": ["console", "companies_file"],
    #     "level": "DEBUG",
    #     "propagate": False,
    # },
    # "apps.inventory": {
    #     "handlers": ["console", "inventory_file"],
    #     "level": "DEBUG",
    #     "propagate": False,
    # },
    # "apps.employees": {
    #     "handlers": ["console", "employees_file"],
    #     "level": "DEBUG",
    #     "propagate": False,
    # },
    # Add more apps here
}

# === FINAL LOGGING CONFIG ===
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": LOGGING_FORMATTERS,
    "handlers": LOGGING_HANDLERS,
    "loggers": LOGGING_LOGGERS,
}