# Generated by Django 5.2.17 on 2026-09-24 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'db_table': 'broker',
            },
        ),
        migrations.CreateModel(
            name='BusinessClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('type', models.CharField(choices=[('other_godown', 'Other Godown'), ('company', 'Company'), ('location', 'Location'), ('my_godown', 'My Godown'), ('my_firm', 'My Firm')], db_index=True, max_length=30)),
                ('flag', models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad'), ('blacklisted', 'Blacklisted'), ('fraud', 'Fraud'), ('unreasonable_claims', 'Unreasonable Claims'), ('neutral', 'Neutral')], db_index=True, max_length=30, null=True)),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Client',
                'verbose_name_plural': 'Business Clients',
                'db_table': 'business_client',
            },
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'db_table': 'commodity',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('sales_order', 'Sales Order'), ('purchase_order', 'Purchase Order')], db_index=True, max_length=20)),
                ('order_no', models.CharField(db_index=True, max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_fulfilled', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='SalesAndTransport.broker')),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='SalesAndTransport.commodity')),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('from_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_from', to='SalesAndTransport.businessclient')),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders_to', to='SalesAndTransport.businessclient')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'db_table': 'transporter',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('bill_no', models.CharField(db_index=True, max_length=10)),
                ('gross_wt', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('bag_nos', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('bag_wt', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('vehicle_no', models.CharField(db_index=True, max_length=12)),
                ('anugya', models.BooleanField(default=False)),
                ('gatepass', models.BooleanField(default=False)),
                ('unload_date', models.DateField(blank=True, null=True)),
                ('rcvd_wt', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('rent', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adv_by_client', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('adv_by_firm', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('final_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('paid', 'Paid')], db_index=True, default='pending', max_length=20)),
                ('wt_rcpt_src', models.ImageField(blank=True, null=True, upload_to='transport/weight_receipts/source/')),
                ('wt_rcpt_dst', models.ImageField(blank=True, null=True, upload_to='transport/weight_receipts/destination/')),
                ('billing_firm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports_billed', to='SalesAndTransport.businessclient')),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='SalesAndTransport.commodity')),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('from_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports_from', to='SalesAndTransport.businessclient')),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('to_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports_to', to='SalesAndTransport.businessclient')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='SalesAndTransport.transporter')),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
                'db_table': 'transport',
            },
        ),
        migrations.CreateModel(
            name='TransportItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_items', to='SalesAndTransport.order')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SalesAndTransport.transport')),
            ],
            options={
                'verbose_name': 'Transport Item',
                'verbose_name_plural': 'Transport Items',
                'db_table': 'transport_items',
            },
        ),
        migrations.AddIndex(
            model_name='broker',
            index=models.Index(fields=['name'], name='broker_name_adef8e_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['name', 'type'], name='business_cl_name_c292ca_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['city', 'type'], name='business_cl_city_b84838_idx'),
        ),
        migrations.AddIndex(
            model_name='businessclient',
            index=models.Index(fields=['flag', 'is_active'], name='business_cl_flag_ed69f4_idx'),
        ),
        migrations.AddIndex(
            model_name='commodity',
            index=models.Index(fields=['name'], name='commodity_name_b1947e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_no'], name='order_order_n_4c2cc7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['type', 'status'], name='order_type_dde0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['from_client', 'status'], name='order_from_cl_56d0b3_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['to_client', 'status'], name='order_to_clie_f73477_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['commodity', 'status'], name='order_commodi_061b96_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker', 'status'], name='order_broker__4b9d6a_idx'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['name'], name='transporter_name_3570e2_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['bill_no'], name='transport_bill_no_3b5686_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['vehicle_no'], name='transport_vehicle_e65a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['status'], name='transport_status_ead7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['billing_firm', 'status'], name='transport_billing_835a81_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['from_client', 'status'], name='transport_from_cl_83d8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['to_client', 'status'], name='transport_to_clie_087133_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['commodity', 'status'], name='transport_commodi_1f454f_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['transporter', 'status'], name='transport_transpo_38b90b_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['unload_date'], name='transport_unload__6421cf_idx'),
        ),
        migrations.AddIndex(
            model_name='transportitems',
            index=models.Index(fields=['transport'], name='transport_i_transpo_f009f4_idx'),
        ),
        migrations.AddIndex(
            model_name='transportitems',
            index=models.Index(fields=['order'], name='transport_i_order_i_bc98f1_idx'),
        ),
    ]
