# Generated by Django 5.2.17 on 2026-09-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='wt_rcpt_dst',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='wt_rcpt_src',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
