# Generated by Django 5.2.17 on 2026-09-25 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0002_alter_transport_wt_rcpt_dst_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('unload_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bulk Transport',
                'verbose_name_plural': 'Bulk Transports',
                'db_table': 'bulk_transport',
            },
        ),
        migrations.AddField(
            model_name='broker',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='broker',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='location_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_unit',
            field=models.CharField(choices=[('mt', 'Mt'), ('quintal', 'Quintal'), ('kg', 'Kg')], db_index=True, default='quintal', max_length=10),
        ),
        migrations.AddField(
            model_name='transport',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='agency',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transportitems',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='from_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_from', to='SalesAndTransport.businessclient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('draft', 'Draft')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='to_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_to', to='SalesAndTransport.businessclient'),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['agency'], name='transporter_agency_f40d82_idx'),
        ),
        migrations.AddIndex(
            model_name='transporter',
            index=models.Index(fields=['city'], name='transporter_city_cf1f86_idx'),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='c_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='d_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='m_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transport',
            name='bulk_transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_transport', to='SalesAndTransport.bulktransport'),
        ),
        migrations.AddIndex(
            model_name='bulktransport',
            index=models.Index(fields=['title'], name='bulk_transp_title_a72271_idx'),
        ),
    ]
