# Generated by Django 5.2.17 on 2026-09-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0003_bulktransport_broker_city_broker_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
