# Generated by Django 5.2.17 on 2026-09-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0004_alter_commodity_name_alter_commodity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='quantity_unit',
            field=models.CharField(choices=[('mt', 'Mt'), ('quintal', 'Quintal'), ('kg', 'Kg')], db_index=True, default='quintal', max_length=10),
        ),
        migrations.AlterField(
            model_name='transport',
            name='bill_no',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='from_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transports_from', to='SalesAndTransport.businessclient'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('paid', 'Paid'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='to_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transports_to', to='SalesAndTransport.businessclient'),
        ),
    ]
