# Generated by Django 5.2.17 on 2026-09-26 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0005_transport_quantity_unit_alter_transport_bill_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transports', to='SalesAndTransport.transporter'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='vehicle_no',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
    ]
