# Generated by Django 5.2.17 on 2026-09-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0006_alter_transport_transporter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulktransport',
            name='unload_date',
        ),
    ]
