# Generated by Django 5.2.17 on 2026-09-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0007_remove_bulktransport_unload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='broker',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bulktransport',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessclient',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transport',
            name='bill_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='agency',
            field=models.CharField(blank=True, db_index=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
