# Generated by Django 5.2.17 on 2026-09-29 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0009_bulk_order_relation_and_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GodownTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('remaining_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('reversal', 'Reversal')], max_length=10)),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='godown_transactions', to='SalesAndTransport.commodity')),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='godown_transactions', to='SalesAndTransport.businessclient')),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='SalesAndTransport.godowntransaction')),
                ('transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='godown_transactions', to='SalesAndTransport.transport')),
            ],
            options={
                'verbose_name': 'Godown Transaction',
                'verbose_name_plural': 'Godown Transactions',
                'db_table': 'godown_transaction',
                'indexes': [models.Index(fields=['godown', 'commodity'], name='godown_tran_godown__44909b_idx'), models.Index(fields=['godown', 'commodity', '-id'], name='godown_tran_godown__efbdfb_idx'), models.Index(fields=['transport'], name='godown_tran_transpo_71afa4_idx'), models.Index(fields=['transaction_type'], name='godown_tran_transac_f6aa0d_idx'), models.Index(fields=['reversal_of'], name='godown_tran_reversa_58474a_idx')],
            },
        ),
    ]
