# Generated by Django 5.2.17 on 2026-10-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0011_purchaseordersequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='rent_type',
            field=models.CharField(choices=[('fix', 'Fix'), ('per_unit', 'Per Unit')], db_index=True, default='per_unit', max_length=20),
        ),
    ]
