# Generated by Django 5.2.17 on 2026-10-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0012_transport_rent_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='bill_hammali',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='commodity',
            name='fill_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='commodity',
            name='mandi_hammali',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
