# Generated by Django 5.2.17 on 2026-10-03 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0014_labour_tempo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='labour',
        ),
    ]
