# Generated by Django 5.2.17 on 2026-10-03 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0015_delete_labour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('c_at', models.DateTimeField(auto_now_add=True)),
                ('m_at', models.DateTimeField(auto_now=True)),
                ('d_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('c_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('d_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('m_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Labour',
                'verbose_name_plural': 'Labours',
                'db_table': 'labour',
                'indexes': [models.Index(fields=['name'], name='labour_name_40a8cf_idx')],
            },
        ),
    ]
