# Generated by Django 5.2.17 on 2026-10-03 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0016_labour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='final_paid',
            new_name='extra_paid',
        ),
    ]
