# Generated by Django 5.2.17 on 2026-10-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0017_rename_final_paid_transport_extra_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='loading_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
