# Generated by Django 5.2.17 on 2026-10-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0018_transport_loading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='final_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
