# Generated by Django 5.2.17 on 2026-10-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0019_transport_final_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='shortage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
