# Generated by Django 5.2.17 on 2026-10-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0020_transport_shortage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportitems',
            name='order_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
