# Generated by Django 5.2.17 on 2026-10-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0022_businessclientprofilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransport',
            name='bill_no',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='billing_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_transports_billed', to='SalesAndTransport.businessclient'),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='loading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_transports', to='SalesAndTransport.order'),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='to_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_transports_to', to='SalesAndTransport.businessclient'),
        ),
        migrations.AddField(
            model_name='bulktransport',
            name='transporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_transports', to='SalesAndTransport.transporter'),
        ),
    ]
