# Generated by Django 5.2.17 on 2026-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0023_bulktransport_bill_no_bulktransport_billing_firm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivery', 'Delivery'), ('finance', 'Finance'), ('paid', 'Paid'), ('draft', 'Draft')], db_index=True, default='draft', max_length=20),
        ),
    ]
