# Generated by Django 5.2.17 on 2026-10-06 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0024_bulktransport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransport',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bulk_commodity', to='SalesAndTransport.commodity'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commodity', to='SalesAndTransport.commodity'),
        ),
    ]
