# Generated by Django 5.2.17 on 2026-10-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0025_bulktransport_commodity_alter_transport_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='account_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='bank',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='branch',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transporter',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
