# Generated by Django 5.2.17 on 2026-10-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0026_transporter_account_name_transporter_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='maan_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
