# Generated by Django 5.2.17 on 2026-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0027_businessclient_maan_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulktransport',
            name='rcvd_wt',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
