# Generated by Django 5.2.17 on 2026-10-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0028_bulktransport_rcvd_wt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulktransport',
            old_name='rcvd_wt',
            new_name='total_rcvd_wt',
        ),
    ]
