# Generated by Django 5.2.17 on 2026-10-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalesAndTransport', '0029_rename_rcvd_wt_bulktransport_total_rcvd_wt'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessclient',
            name='contact_name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='pri_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='businessclient',
            name='sec_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
