# Generated by Django 5.2.17 on 2026-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockPassCore', '0002_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile/'),
        ),
    ]
