# Generated by Django 5.2.17 on 2026-10-06 08:37

import StockPassCore.models.users
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockPassCore', '0005_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', StockPassCore.models.users.UserManager()),
            ],
        ),
    ]
